services:
  - type: web
    name: todo-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
